---
- name: Install prereqs
  apt:
    name: '{{item}}'
    state: latest
    update_cache: yes
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Get docker repo
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

- name: Add docker repo
  shell: "echo 'deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable' | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"

- name: Install docker
  apt:
    name: '{{item}}'
    state: latest
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Make docker is running
  systemd:
    state: started
    name: docker